DISABLE_AUTO_UPDATE=true
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

# Useful oh-my-zsh plugins for Le Wagon bootcamps
plugins=(git gitfast last-working-dir common-aliases zsh-syntax-highlighting history-substring-search direnv)

export HOMEBREW_NO_ANALYTICS=1

# Disable warning about insecure completion-dependent directories
ZSH_DISABLE_COMPFIX=true

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"

alias e="open ."
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args "$@" ;} # mdls -name kMDItemCFBundleIdentifier /Applications/Visual\ Studio\ Code.app
c () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args "$@" ;}
v () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCodeInsiders" --args "$@" ;}
b () { VSCODE_CWD="$PWD" open -n -b "com.vscodium" --args "$@" ;}
n () { cursor "$@" ;}
j () { jupyter notebook "$@" ;}
tsinghua-pip () { unset all_proxy; pip install -i https://pypi.tuna.tsinghua.edu.cn/simple "$@" ;}
m () { open -a /Applications/Movavi\ Video\ Suite\ 22.app/Contents/MacOS/ScreenRecorder;}

bilibili () { bbdown -p ALL "$@" ;}

unalias rm # No interactive rm by default (brought by plugins/common-aliases)
unalias lt # we need `lt` for https://github.com/localtunnel/localtunnel
unalias g
unalias p
unalias l
unalias h
unalias t
unalias 1
alias g="cd ~/Documents/GitHub/"
alias p="cd ~/PycharmProjects"
alias z="code ~/.zshrc"
alias l="ls"
alias y="yt-dlp"
alias a="cd ~/PycharmProjects/adblockplus && code ."
alias p1="export all_proxy=http://127.0.0.1:1087"
alias p0="unset all_proxy"
alias 1="export all_proxy=http://127.0.0.1:1087"
alias 0="unset all_proxy"

# Load pyenv (to manage your Python versions)
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
type -a pyenv > /dev/null && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init - 2> /dev/null)" && RPROMPT+='[🐍 $(pyenv version-name)]'

export PATH="/opt/homebrew/bin:${PATH}:/usr/local/sbin"
export PATH=$PATH:/Users/lunde/hugo

# Store your own aliases in the ~/.aliases file and load the here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Set ipdb as the default Python debugger
export PYTHONBREAKPOINT=ipdb.set_trace

# export all_proxy=http://127.0.0.1:1087
