DISABLE_AUTO_UPDATE=true

alias e="open ."
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
c () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
v () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCodeInsiders" --args $* ;}
b () { VSCODE_CWD="$PWD" open -n -b "com.vscodium" --args $* ;}
m () { open -a /Applications/Movavi\ Video\ Suite\ 22.app/Contents/MacOS/ScreenRecorder;}
movavi () { open -a /Applications/Movavi\ Video\ Suite\ 22.app/Contents/MacOS/ScreenRecorder;}

ZSH=$HOME/.oh-my-zsh

# You can change the theme with another one from https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="robbyrussell"

# Useful oh-my-zsh plugins for Le Wagon bootcamps
plugins=(git gitfast last-working-dir common-aliases zsh-syntax-highlighting history-substring-search direnv)

# (macOS-only) Prevent Homebrew from reporting - https://github.com/Homebrew/brew/blob/master/docs/Analytics.md
export HOMEBREW_NO_ANALYTICS=1

# Disable warning about insecure completion-dependent directories
ZSH_DISABLE_COMPFIX=true

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"
unalias rm # No interactive rm by default (brought by plugins/common-aliases)
unalias lt # we need `lt` for https://github.com/localtunnel/localtunnel
unalias g
unalias p
unalias l
unalias h
unalias t
alias g="cd ~/Documents/GitHub/"
alias p="cd ~/PycharmProjects"
alias z="code ~/.zshrc"
alias n="jupyter notebook"
alias j="jupyter lab"
alias l="jupyter lab"
alias a="cd ~/PycharmProjects/adblockplus && code ."
alias t="cd ~/PycharmProjects/lunde.top && code ."
alias o="cd ~/PycharmProjects/machine-learning-ocademy && code ."
alias r="cd ~/Documents/GitHub/reveurmichael-machine-learning && code ."
alias s="git stash"
alias y="export all_proxy=http://127.0.0.1:1087"
alias u="unset all_proxy"
alias f="git fetch origin && git fetch upstream"


# Load pyenv (to manage your Python versions)
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
type -a pyenv > /dev/null && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init - 2> /dev/null)" && RPROMPT+='[🐍 $(pyenv version-name)]'


# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:/opt/homebrew/bin:${PATH}:/usr/local/sbin"
export PATH=$PATH:/Users/lunde/hugo



# Store your own aliases in the ~/.aliases file and load the here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Set ipdb as the default Python debugger
export PYTHONBREAKPOINT=ipdb.set_trace

export all_proxy=http://127.0.0.1:1087